Upload page
Meme-of-the-Day/meme-of-the-day pull request #39
Opened 2020-12-28 14:23 UTC by shad-k

- Upload page UI
- Sign transaction
- Approve

Right now the request to store the meme metadata fails because of the new signature field added.
@sylar217 You'll need to check how to store the signature.

2021-01-09 07:55 UTC, sylar217 commented on src/pages/Upload.tsx
> +                await textile.deleteMemeFromBucket(meme);
This is just putting the meme on sale right? Minting has already happened in another contract call, so we shouldn't delete the meme from textile.

2021-01-09 07:55 UTC, sylar217 commented on src/pages/Upload.tsx
> +              await textile.deleteMemeFromBucket(meme);
Even this is just signature for sale, minting has already happened, we shouldn't delete from backend.

2021-01-09 07:55 UTC, sylar217 commented on src/pages/Upload.tsx
> +          await textile.deleteMemeFromBucket(meme);
Same, this is just part of sales, minting has already happened.

2021-01-09 19:46 UTC, matprime commented on src/utils/Types.ts
> +  sellApprovalSignature?: SignedTransaction;
I talked to Lorenzo about that before, he said to me that signature is basically string. So I ques using string or hash string could work. Here are input parameters of buy smart contract function, which needs signature as input to check if money sent from buyer is correct. It need 3 parameters representing signature v,r,s:

    /**
     * @notice Buys token
     * @param tokenId       the id of the token to buy
     * @param price         the price of the token on sale
     * @param voters        array of voters on the meme
     * @param votes         array of votes of the voters
     * @param payCreator    defines if creator has to be paid or not
     * @param v             v part of the seller's signature
     * @param r             r part of the seller's signature
     * @param s             s part of the seller's signature
     */
    function buy(
        uint256 tokenId,
        uint256 price,
        address payable[] calldata voters,
        uint256[] calldata votes,
        bool payCreator,
        uint8 v,
        bytes32 r,
        bytes32 s
    )

2021-01-15 18:09 UTC, matprime requested changes
I have found 2 bugs after this commit:
1. When meme is created with price, browser developer console throws error when signing:
MetaMask - RPC Error: Provided chainId "3431" must match the active chainId "1337" 
There is also no Metamask window popping out to make a signature.
2. When is meme created and put on sale, dapp shows two copies of this meme

Update:
1. error was produced because of incorrect configuration in Metamask
2. Introducing fix for creation of duplicated memes with next commit

2021-01-20 20:17 UTC, merged